export const getGreeting = (hour: number, username: string) => {
    const minute = new Date().getMinutes();

    // ultra rare easter eggs (very specific times)
    if (hour === 3 && minute === 33) {
        return `3:33 AM demon hour, ${username}!`;
    }
    if (hour === 4 && minute === 20) {
        return `4:20 nice, ${username} 🌿`;
    }

    // rare easter eggs (~5% chance total)
    const rareChance = Math.random();
    if (rareChance < 0.01) {
        return `Nyaa~ ${username}!`;
    }
    if (rareChance >= 0.01 && rareChance < 0.02) {
        return `Heil Eggler, ${username}!`;
    }
    if (rareChance >= 0.02 && rareChance < 0.03) {
        return `${username} has unlocked: Rare Greeting #${Math.floor(Math.random() * 999) + 1}!`;
    }
    if (rareChance >= 0.03 && rareChance < 0.04) {
        return `The developer is watching you, ${username}...`;
    }
    if (rareChance >= 0.04 && rareChance < 0.05) {
        return `Your desktop called, it wants personality, ${username}`;
    }

    const greetings = {
        night: [
            `Good night, ${username}!`,
            `${username} is up late!`,
            `Still awake, ${username}?`,
            `Burning the midnight oil, ${username}?`,
            `Tomorrow is not going to be your day. Same goes for this year!`,
            `${username} vs sleep: sleep is winning`,
            `Late Night gooner ${username} appears!`,
            `Can't sleep, ${username}?`,
            `Late night vibes, ${username}!`,
            `Discord mod hours, ${username}?`,
            `Who hurt you ${username}?`,
            `${username} in the dark hours!`,
            `Restless night, ${username}?`,
            `It's okay to open Wallpaper Engines at night instead of sleeping :D`,
            `Anime tiddies keeyping ya up? ${username}?`,
            `Stars are out, ${username}!`,
            `What's keeping you up, ${username}?`,
            `Late night scroll, ${username}?`,
            `It's past 9pm ${username}, sleep?`,
            `Insomnia hitting, ${username}?`,
            `It's okay, i won't judge you for being awake ${username}`,
            `Should probably sleep, ${username}...`,
            `One more hour, ${username}?`,
            `Will you be obsessed with me? hm?`,
            `The night is young, ${username}!`,
            `What to do if the world ends? ${username}, Set a live wallpaper!`,
            `3am thoughts, ${username}?`,
            `Sleep is overrated anyway, ${username}!`,
            `Are you alright?`,
            `Just one more thing, ${username}?`,
            `SLEEP NOW, ${username}!`,
            `Unemployed Activities, ${username}?`,
            `Are you sure you want to do this?`,
            `Please stop being sad ${username}?`,
            `The demons are active, ${username}!`,
            `Why are you still here, ${username}?`,
            `You can rest now, ${username}.`,
            `Midnight thoughts getting to you, ${username}?`,
            `Tomorrow is a new day... if you ever sleep, ${username}.`,
            `Your computer needs rest too, ${username}.`,
            `Is it too late for coffee, ${username}?`,
            `Night owl or just procrastinating, ${username}?`,
            `Touch grass tomorrow, ${username}`,
            `Your sleep schedule is cooked, ${username}`,
            `Vampire ${username} awakens!`,
            `Your eye bags called, ${username}`,
            `Tomorrow you is gonna hate you, ${username}`,
            `Did you lock your doors, ${username}?`,
            `The FBI agent is watching you sleep, ${username}.`,
            `Go to bed or the sleep paralysis demon wins, ${username}.`,
            `Do you ever just... exist? ${username}?`,
            `Please, for the love of God, close the tabs, ${username}.`,
            `The monsters under your bed are judging your search history, ${username}.`,
            `You really have no life, do you ${username}?`,
            `Ah yes, 3 AM. The perfect time to stare at a glowing rectangle, ${username}.`,
            `You look like a raccoon that found a smartphone, ${username}.`,
            `Bags under your eyes are designer at this point, ${username}.`,
            `Are you ever going to touch a real woman, ${username}?`,
            `Your ancestors survived the ice age for you to do this, ${username}?`,
            `I'd tell you to go to sleep, but we both know you won't, ${username}.`,
            `If depression was a time of day, this would be it, ${username}.`,
        ],
        morning: [
            `Good morning, ${username}!`,
            `${username} rises early!`,
            `Morning bbg, ${username}!`,
            `Rise and shine, ${username}!`,
            `Coffee time, ${username}?`,
            `Fresh start, ${username}!`,
            `${username} greets the day!`,
            `Early bird ${username}!`,
            `New day, ${username}!`,
            `Sunrise energy, ${username}!`,
            `Ready for the day, ${username}?`,
            `Morning glory, ${username}!`,
            `Wakey wakey, ${username}!`,
            `Need that coffee, ${username}?`,
            `Let's get this bread, ${username}!`,
            `Motivated this morning, ${username}?`,
            `Feeling fresh, ${username}?`,
            `Another day, another slay, ${username}!`,
            `You got this today, ${username}!`,
            `Breakfast or vibes lol, ${username}?`,
            `Time to conquer, ${username}!`,
            `Morning sunshine, ${username}!`,
            `What's the plan today, ${username}?`,
            `Bright and early, ${username}!`,
            `Today's gonna be good, ${username}!`,
            `Please Brush your teeth ${username}? uwu?`,
            `${username} escaped the bed dimension!`,
            `Five more minutes x20, ${username}?`,
            `The grind never stops, ${username}!`,
            `Snooze button abuser ${username} appears!`,
            `You look like a zombie, ${username}.`,
            `Welcome to another episode of 'I should have slept earlier', ${username}.`,
            `Ah, ${username}, awake and ready to suffer!`,
            `Blinking aggressively at the screen, ${username}?`,
            `Good morning! Time to fake being a functioning member of society, ${username}.`,
            `Your breath stinks even through the screen, ${username}. Go brush.`,
            `Wake up, wagie, ${username}! The corporate machine demands blood.`,
            `Did you actually sleep, or did you just pass out, ${username}?`,
            `Another day of putting the 'L' in living, ${username}!`,
            `You woke up today. My condolences, ${username}.`,
            `Look who decided to join the land of the living, ${username}.`,
        ],
        afternoon: [
            `Good afternoon, ${username}!`,
            `${username} is here!`,
            `Hey ${username}!`,
            `${username} returns!`,
            `Coffee and work time, ${username}?`,
            `Enjoying the day, ${username}?`,
            `How's your day going, ${username}?`,
            `Midday check-in, ${username}!`,
            `${username} in action!`,
            `Productive vibes, ${username}?`,
            `Afternoon energy, ${username}!`,
            `Halfway there, ${username}!`,
            `Keeping busy, ${username}?`,
            `What's cooking, ${username}?`,
            `Lunch break over, ${username}?`,
            `Back to the grind, ${username}?`,
            `Doing okay, ${username}?`,
            `Need a break, ${username}?`,
            `Staying focused, ${username}?`,
            `How's the hustle, ${username}?`,
            `Powering through, ${username}?`,
            `Almost there, ${username}!`,
            `Afternoon pick-me-up time, ${username}?`,
            `What's new, ${username}?`,
            `Crushing it, ${username}?`,
            `Vibing today, ${username}?`,
            `Making moves, ${username}?`,
            `Day treating you well, ${username}?`,
            `${username} returns from touching grass!`,
            `Post-lunch coma incoming, ${username}?`,
            `Still procrastinating, ${username}?`,
            `The day is escaping, ${username}!`,
            `Stop pretending to work, ${username}.`,
            `Is it 5 PM yet? No? Sucks to be you, ${username}.`,
            `Ah, the daily 2 PM existential crisis, ${username}?`,
            `Go get some water, you dried up raisin, ${username}.`,
            `Mid-day burnout hitting hard, huh ${username}?`,
            `Are you paid enough for this, ${username}? (You aren't).`,
            `Look at you, pretending to be productive, ${username}. Cute.`,
            `You have the posture of a cooked shrimp, ${username}. Sit up.`,
            `Afternoon slump? More like a permanent decline, ${username}.`,
            `I can hear your brain cells dying from here, ${username}.`,
        ],
        evening: [
            `Good evening, ${username}!`,
            `${username} returns!`,
            `Welcome back, ${username}!`,
            `I know you procastrinated, ${username}!`,
            `I will do it tomorrow -${username}`,
            `I have time -${username} (no you don't)`,
            `Evening huh?, ${username}!`,
            `How was your day, ${username}?`,
            `Winding down, ${username}?`,
            `${username} arrives home!`,
            `You alright, ${username}?`,
            `Time to relax, ${username}?`,
            `${username} at dusk!`,
            `End of day, ${username}!`,
            `Cozy hours, ${username}!`,
            `Settling in, ${username}?`,
            `Ready to unwind, ${username}?`,
            `Finally some rest, ${username}?`,
            `Long day, ${username}?`,
            `Time for you, ${username}!`,
            `Survived another one, ${username}?`,
            `Feet up time, ${username}!`,
            `What's for dinner, ${username}?`,
            `Netflix and chill, ${username}?`,
            `You deserve a break, ${username}!`,
            `Made it through, ${username}!`,
            `Peace at last, ${username}?`,
            `How you feeling, ${username}?`,
            `Time to decompress, ${username}!`,
            `Golden hour huh, ${username}!`,
            `Day went by fast huh, ${username}?`,
            `${username} survived another one!`,
            `Time to rot on the couch, ${username}?`,
            `Productivity? Never heard of her, ${username}`,
            `Tomorrow's problem is tomorrow's problem, ${username}`,
            `Sunset vibes, ${username}!`,
            `Don't forget to hydrate, ${username}!`,
            `Why are you still single ${username}.`,
            `Good work today, ${username}.`,
            `Reflecting on the day, ${username}?`,
            `You survived! Barely, but you did it, ${username}.`,
            `Time to regret all the things you didn't do today, ${username}.`,
            `Dinner time or cereal time, ${username}?`,
            `The sun sets on another day of questionable choices, ${username}.`,
            `Evening, ${username}. Time to rot on TikTok for 4 hours.`,
            `The day is over and you achieved absolutely nothing, ${username}. Congrats.`,
            `Just give up and order pizza, ${username}. We both know you can't cook.`,
            `You made it to the evening, ${username}. Now what? Exactly. Nothing.`,
            `Time to drown your sorrows in digital escapism, ${username}.`,
            `Another day closer to the void, ${username}!`,
        ],
    };

    let timeOfDay: keyof typeof greetings;
    if (hour >= 21 || hour < 6) timeOfDay = 'night'; // 9pm to 6am
    else if (hour >= 6 && hour < 12) timeOfDay = 'morning';
    else if (hour >= 12 && hour < 18) timeOfDay = 'afternoon';
    else timeOfDay = 'evening'; // 6pm to 9pm

    const messages = greetings[timeOfDay];
    return messages[Math.floor(Math.random() * messages.length)];
};
